# Monthly Security Audit Script
# Runs comprehensive Shannon security test and archives report

param(
    [string]$BackendUrl = "http://localhost:8000"
)

function Write-ColorOutput {
    param([string]$Message, [string]$Color = "White")
    Write-Host $Message -ForegroundColor $Color
}

Write-ColorOutput "`n╔══════════════════════════════════════╗" "Cyan"
Write-ColorOutput "║  Monthly Security Audit - StudyPulse ║" "Cyan"
Write-ColorOutput "╚══════════════════════════════════════╝`n" "Cyan"

$date = Get-Date
$monthYear = $date.ToString("yyyy-MM")
$fullDate = $date.ToString("yyyy-MM-dd")

Write-ColorOutput "Audit Date: $fullDate" "Yellow"
Write-ColorOutput "Target: $BackendUrl`n" "Yellow"

# Create directories
$dirs = @(
    "security/reports",
    "security/reports/archive",
    "security/fixes"
)

foreach ($dir in $dirs) {
    if (-not (Test-Path $dir)) {
        New-Item -ItemType Directory -Force -Path $dir | Out-Null
    }
}

# Run Shannon
Write-ColorOutput "Running comprehensive security scan...`n" "Cyan"
$reportFile = "security/reports/audit-$monthYear.md"

try {
    .\scripts\run-shannon-security-test.ps1 -BackendUrl $BackendUrl -OutputFile $reportFile -Verbose

    if ($LASTEXITCODE -eq 0) {
        Write-ColorOutput "`n✓ Security audit completed!" "Green"

        # Create audit summary
        $summary = @"
# Monthly Security Audit Summary
**Date:** $fullDate
**Target:** $BackendUrl
**Report:** $reportFile

## Status
- [ ] Report reviewed
- [ ] CRITICAL issues addressed
- [ ] HIGH issues scheduled for fix
- [ ] MEDIUM issues added to backlog
- [ ] Report archived

## Actions Required
1. Review full report: $reportFile
2. Create GitHub issues for HIGH+ findings
3. Schedule fix timeline
4. Update this summary when complete

---
*Auto-generated by monthly-security-audit.ps1*
"@

        $summaryFile = "security/audit-$monthYear-summary.md"
        $summary | Out-File $summaryFile -Encoding UTF8

        Write-ColorOutput "`nAudit summary created: $summaryFile" "Green"
        Write-ColorOutput "`nNext steps:" "Cyan"
        Write-ColorOutput "  1. Review report: code $reportFile" "White"
        Write-ColorOutput "  2. Update summary: code $summaryFile" "White"
        Write-ColorOutput "  3. Create GitHub issues for findings" "White"
        Write-ColorOutput "  4. Track remediation progress`n" "White"
    }
} catch {
    Write-ColorOutput "`n✗ Audit failed: $_" "Red"
    exit 1
}

# Archive old reports (keep last 12 months)
Write-ColorOutput "Archiving old reports..." "Cyan"
$reports = Get-ChildItem "security/reports/audit-*.md" | Sort-Object LastWriteTime -Descending
if ($reports.Count -gt 12) {
    $toArchive = $reports | Select-Object -Skip 12
    foreach ($report in $toArchive) {
        Move-Item $report.FullName "security/reports/archive/" -Force
        Write-ColorOutput "  Archived: $($report.Name)" "Yellow"
    }
}

Write-ColorOutput "`n✓ Monthly security audit complete!`n" "Green"
